#define SPO2_ADDR           0x55

// SPO2 constants
#define DISABLE             0x00
#define ENABLE              0x01
#define ALGO_CMD_DELAY      45
#define CMD_DELAY           2
#define MAXFAST_ARRAY_SIZE  6
#define SET_FORMAT          0x00
#define READ_FORMAT         0x01
#define WRITE_SET_THRESHOLD 0x01
#define HUB_STATUS          0x00
#define SET_DEVICE_MODE     0x01
#define READ_DEVICE_MODE    0x02
#define OUTPUT_MODE         0x10
#define READ_OUTPUT_MODE    0x11
#define READ_DATA_OUTPUT    0x12
#define ENABLE_SENSOR       0x44
#define READ_SENSOR_MODE    0x45
#define READ_ALG_CONFIG     0x51
#define READ_AGC_NUM_SAMPLES      0x00
#define READ_AGC_NUM_SAMPLES_ID   0x03
#define ENABLE_ALGORITHM    0x52
#define ALGO_DATA           0x02
#define ALGO_DATA_AND_SENS  0x03
#define NUM_SAMPLES         0x00
#define READ_DATA           0x01
#define ENABLE_MAX30101     0x03
#define ENABLE_ACCEL	    0x04
#define ENABLE_AGC_ALGO     0x00
#define ENABLE_WHRM_ALGO    0x02